In [59]:
import numpy as np

In [60]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [61]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [62]:
#get dimension
A = a.ndim
B = b.ndim
print(A, B)

1 2


In [63]:
#get shape
C = a.shape
D = b.shape
print (C,D)

(3,) (2, 3)


In [64]:
# get type
print (a.dtype, b.dtype)

int32 float64


In [65]:
#get size
print (a.itemsize,b.itemsize)

4 8


In [66]:
#get total size
#a.size and a.nbytes gives the same output
print (a.size)

3


In [67]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,1,2,3,4]])
print (a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10  1  2  3  4]]


In [68]:
a.shape

(2, 7)

In [69]:
#get a specific element [f,c]
a[1,5]

3

In [70]:
#get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [71]:
#get a specific column 
a[:,0]

array([1, 8])

In [72]:
# [startindex:endindex:stepsize]
a = np.array([[1,2,3,4,5,6,7],[8,9,10,1,2,3,4]])
a[0, 1:6:2]

array([2, 4, 6])

In [73]:
a[1,5] = 20
print (a)
a[:,5] = 5
print (a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10  1  2 20  4]]
[[ 1  2  3  4  5  5  7]
 [ 8  9 10  1  2  5  4]]


In [74]:
#all 0s matrix
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [75]:
#all 1s matrix
np.ones((2,3,4,2), dtype='int16')

array([[[[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]]]], dtype=int16)

In [76]:
#matrix with only one value
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [77]:
#any other number (full_like)
np.full_like(a,10)

array([[10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10]])

In [78]:
# random decimal numbers 
np.random.rand(4,2)

array([[0.01243042, 0.95827475],
       [0.10431043, 0.88330553],
       [0.52459346, 0.70017254],
       [0.87343715, 0.57576978]])

In [79]:
#random decimal numbers using the shape of a
np.random.random_sample(a.shape)

array([[0.79237331, 0.72623058, 0.22846231, 0.49891633, 0.63634204,
        0.75501167, 0.94024121],
       [0.60758355, 0.13863594, 0.69076216, 0.28183435, 0.82628934,
        0.87738876, 0.04522201]])

In [80]:
#random integer values
print (np.random.randint(7, size=(3,3)))
#specifies limit of random numbers, second limit is exclusive
print (np.random.randint(4,7, size=(3,3)))

[[6 2 4]
 [0 1 1]
 [5 0 6]]
[[6 4 5]
 [5 6 5]
 [6 6 4]]


In [81]:
#identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [82]:
#repeating an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis = 0)
print(r1)
r1 = np.repeat(arr,3, axis = 1)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 2 2 2 3 3 3]]


In [83]:
output = np.ones((5,5))
print (output)

z = np.zeros((3,3))
z[1,1] = 9
print (z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [84]:
#copying arrays
a = np.array ([1,2,3])
b = a.copy()
print(b)
b = a
b[0] = 100
print(a)

[1 2 3]
[100   2   3]


In [85]:
#element wise arithmetic
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [86]:
a+2

array([3, 4, 5, 6])

In [87]:
a - 2

array([-1,  0,  1,  2])

In [88]:
a * 2

array([2, 4, 6, 8])

In [89]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [90]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [91]:
a ** 2

array([ 1,  4,  9, 16])

In [92]:
#take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [93]:
#matrix algebra
a = np.ones((2,3))
print (a)

b = np.full((3,2), 2)
print (b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [94]:
c = np.identity(3)
np.linalg.det(c)

1.0

In [95]:
#statistics
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [98]:
print (np.min(stats,axis=0))
print (np.min(stats))

[1 2 3]
1


In [99]:
print(np.max(stats, axis=0))
print(np.max(stats, axis=1))

[4 5 6]
[3 6]


In [100]:
np.sum(stats, axis = 0)

array([5, 7, 9])

In [102]:
np.sum(stats)

21

In [105]:
#reshaping the arrays (allowed until the number of elements are the same)

before = np.array([[1,2,3,4],[5,6,7,8]])
print (before)

after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [106]:
#vertically stacking matrices

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [107]:
#horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [109]:
#load data from file into a numpy aray
filedata = np.genfromtxt('test.csv', delimiter=',')
filedata = filedata.astype('int32')
filedata

C:\Users\Advika\AppData\Local\Temp\ipykernel_8264\1300053272.py:3: RuntimeWarning: invalid value encountered in cast
  filedata = filedata.astype('int32')


array([[-2147483648, -2147483648, -2147483648, ..., -2147483648,
        -2147483648, -2147483648],
       [          8,        1970,           3, ...,        2006,
               2006,      281000],
       [          6,        1632,           1, ...,        1958,
               1988,      139000],
       ...,
       [          6,         848,           2, ...,        2003,
               2003,      140000],
       [          7,        1266,           2, ...,        2007,
               2007,      159895],
       [          6,        1484,           2, ...,        2005,
               2007,      178900]])

In [110]:
#boolean masking and advanced indexing
filedata > 50 

array([[False, False, False, ..., False, False, False],
       [False,  True, False, ...,  True,  True,  True],
       [False,  True, False, ...,  True,  True,  True],
       ...,
       [False,  True, False, ...,  True,  True,  True],
       [False,  True, False, ...,  True,  True,  True],
       [False,  True, False, ...,  True,  True,  True]])

In [112]:
#lists all elements satisfying the condition in an array
filedata[filedata > 50]

array([  1970,    753,   1085, ...,   2005,   2007, 178900])

In [113]:
#indexing with a list in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [115]:
((filedata > 50)  & (filedata < 100))

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])